global:
  imagePullSecrets: []

image:
  registry: ghcr.io
  org: aet-devops26
  repo: team-http-418
  tag: latest
  pullPolicy: IfNotPresent

replicaCount:
  server: 1
  client: 1
  postgres: 1

server:
  port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432
    SPRING_DATASOURCE_USERNAME: postgres

    API_VERSION: v1
    APP_JWT_ACCESS_TOKEN_TTL_SECONDS: "3600"
    APP_REFRESH_TOKEN_TTL_SECONDS: "604800"

genai:
  env:
    GENAI_BASE_URL: http://genai:8000
    GENAI_API_VERSION: v1
    LLM_PROVIDER: cloud

    LOGOS_BASE_URL: https://logos.aet.cit.tum.de
    LOGOS_API_VERSION: v1
    LOGOS_MODEL: openai/gpt-oss-120b

    EMBEDDING_MODEL_CLOUD: Qwen/Qwen3-Embedding-8B

client:
  port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

postgres:
  image: postgres:17
  port: 5432
  database: aidan
  storage: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  env:
    DB_HOST: "db"
    DB_USER: "postgres"
    COURSES_DB_NAME: "courses-data"
    DB_PORT: "5432"
    DATABASE_URL: "postgresql://postgres:password@db:5432/courses-data"

secrets:
  SPRING_DATASOURCE_PASSWORD: "" #will be set by github actions
  APP_JWT_SECRET: "" #will be set by github actions
  DB_PASS: "" #will be set by github actions
  LOGOS_API_KEY: "" #will be set by github actions

ingress:
  enabled: true
  className: nginx
  host: ""
  annotations: {}

namespace: aidan
