namespace: aidan

image:
  tag: latest # Overridden by CI/CD with git SHA

ingress:
  enabled: true
  className: nginx
  host: "aidan.stud.k8s.aet.cit.tum.de"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
    secretName: aidan-tls
global:
  imagePullSecrets:
    - name: ghcr-pull-secret
