services:
  db:
    build: infra/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      COURSES_DB_NAME: ${COURSES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./services/server
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      default:
        aliases:
          - server-service
    depends_on:
      db:
        condition: service_healthy
      user-profile-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pdf-parser:
    build: ./services/pdf-parser
    ports:
      - "8070:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-profile-service:
    build: ./services/user-profile-service
    ports:
      - "8060:8080"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./services/client
      args:
        - API_VERSION=${API_VERSION}
    ports:
      - "3000:80"
    depends_on:
      - server

  genai:
    build: ./services/genai
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/v1/health')\""]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    profiles:
      - local
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list"]
      interval: 30s
      timeout: 10s
      retries: 3

  scraper:
    build: ./services/scraper
    profiles:
      - scraper
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # allow container to reach services on the host machine at host.docker.internal. only for linux compatibility
    depends_on:
      db:
        condition: service_healthy

  scraper-clean:
    build: ./services/scraper
    command: ["--clean"]
    profiles:
      - scraper_clean
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # allow container to reach services on the host machine at host.docker.internal. only for linux compatibility
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  ollama_data:
