services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    image: ghcr.io/aet-devops26/team-http-418/server:${IMAGE_TAG:-latest}
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-profile-service:
    image: ghcr.io/aet-devops26/team-http-418/user-profile-service:${IMAGE_TAG:-latest}
    ports:
      - "8060:8080"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  pdf-parser:
    image: ghcr.io/aet-devops26/team-http-418/pdf-parser:${IMAGE_TAG:-latest}
    ports:
      - "8070:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  genai:
    build: ghcr.io/aet-devops26/team-http-418/genai:${IMAGE_TAG:-latest}
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/v1/health')\""]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db

  client:
    image: ghcr.io/aet-devops26/team-http-418/client:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  pgdata:
