services:
  db:
    build: infra/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      COURSES_DB_NAME: ${COURSES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./services/server
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      default:
        aliases:
          - server-service
    depends_on:
      db:
        condition: service_healthy
      user-profile-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pdf-parser:
    build: ./services/pdf-parser
    ports:
      - "8070:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-profile-service:
    build: ./services/user-profile-service
    ports:
      - "8060:8080"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:8080/v1/health 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./services/client
      args:
        - API_VERSION=${API_VERSION}
    ports:
      - "3000:80"
    depends_on:
      - server

  genai:
    build: ./services/genai
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/v1/health')\""]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    profiles:
      - local
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list"]
      interval: 30s
      timeout: 10s
      retries: 3

  scraper:
    build: ./services/scraper
    profiles:
      - scraper
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # allow container to reach services on the host machine at host.docker.internal. only for linux compatibility
    depends_on:
      db:
        condition: service_healthy

  scraper-clean:
    build: ./services/scraper
    command: ["--clean"]
    profiles:
      - scraper_clean
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # allow container to reach services on the host machine at host.docker.internal. only for linux compatibility
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/helm/aidan-monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./infra/helm/aidan-monitoring/grafana:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=logsInExplore
      - GF_LOG_CONSOLECOLORS=true
    # entrypoint: ["sh", "-c", "/etc/grafana/provisioning/init_grafana.sh"]
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./infra/helm/aidan-monitoring/promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./infra/helm/aidan-monitoring/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${COURSES_DB_NAME}?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  pgdata:
  ollama_data:
  prometheus_data:
  grafana-storage:
  loki-data:
