spring.application.name=http418
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=TRACE
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=TRACE
logging.level.org.springframework.beans.TypeConverterDelegate=TRACE
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true