spring.application.name=http418
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=TRACE
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=TRACE
logging.level.org.springframework.beans.TypeConverterDelegate=TRACE
