spring.application.name=http418
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=TRACE
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=TRACE
logging.level.org.springframework.beans.TypeConverterDelegate=TRACE