apiVersion: v1
kind: Service
metadata:
  name: genai
  namespace: {{ .Values.namespace }}
  labels:
    app: genai
    {{- include "aidan.labels" . | nindent 4 }}
spec:
  selector:
    app: genai
  ports:
    - port: {{ .Values.genai.port }}
      targetPort: {{ .Values.genai.port }}
