apiVersion: v1
kind: Service
metadata:
  name: pdf-parser
  namespace: {{ .Values.namespace }}
  labels:
    app: pdf-parser
    {{- include "aidan.labels" . | nindent 4 }}
spec:
  selector:
    app: pdf-parser
  ports:
    - port: {{ .Values.pdfParser.port }}
      targetPort: {{ .Values.pdfParser.containerPort }}
