apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-profile-service
    {{- include "aidan.labels" . | nindent 4 }}
spec:
  selector:
    app: user-profile-service
  ports:
    - port: {{ .Values.userProfile.port }}
      targetPort: {{ .Values.userProfile.containerPort }}
