package tum.devops.http418;

import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.DependsOn;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import javax.sql.DataSource;

@TestConfiguration
public class TestConfig {
	public static double h2Similarity(String a, String b) {
		return 0.0;
	}

	@Bean
	@Primary
	public DataSource dataSource() {
		return new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2).build();
	}

	@Profile("test")
	@Bean(name = "securityJdbcTemplate")
	@Primary
	public NamedParameterJdbcTemplate securityJdbcTemplate(DataSource dataSource) {
		final NamedParameterJdbcTemplate jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
		jdbcTemplate.getJdbcOperations()
				.execute("CREATE TABLE IF NOT EXISTS credentials (username TEXT PRIMARY KEY, password TEXT NOT NULL)");
		jdbcTemplate.getJdbcOperations().execute(
				"CREATE TABLE IF NOT EXISTS user_authorities (username TEXT NOT NULL, authority TEXT NOT NULL)");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS student_completed_courses (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    username TEXT NOT NULL REFERENCES credentials(username) ON DELETE CASCADE,
				    course_id BIGINT NOT NULL,
				    grade NUMERIC(2,1) CHECK (grade >= 0),
				    credits INT NOT NULL DEFAULT 0 CHECK (credits >= 0),
				    semester_key TEXT,
				    category TEXT,
				    UNIQUE (username, course_id)
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS student_enrolled_courses (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    username TEXT NOT NULL REFERENCES credentials(username) ON DELETE CASCADE,
				    course_id BIGINT NOT NULL,
				    semester_key TEXT,
				    UNIQUE (username, course_id)
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS advisor_conversations (
				    id TEXT PRIMARY KEY,
				    username TEXT NOT NULL REFERENCES credentials(username) ON DELETE CASCADE,
				    title TEXT NOT NULL DEFAULT 'New Conversation',
				    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS advisor_messages (
				    id TEXT PRIMARY KEY,
				    conversation_id TEXT NOT NULL REFERENCES advisor_conversations(id) ON DELETE CASCADE,
				    role TEXT NOT NULL,
				    content TEXT NOT NULL,
				    referenced_courses TEXT DEFAULT '[]',
				    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS student_roadmaps (
				    username TEXT PRIMARY KEY REFERENCES credentials(username) ON DELETE CASCADE,
				    roadmap_json TEXT NOT NULL,
				    status TEXT NOT NULL DEFAULT 'EMPTY',
				    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
				)
				""");
		return jdbcTemplate;
	}

	@Profile("test")
	@Bean(name = "coursesJdbcTemplate")
	@DependsOn("securityJdbcTemplate")
	public NamedParameterJdbcTemplate coursesJdbcTemplate(DataSource dataSource) {
		final NamedParameterJdbcTemplate jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
		jdbcTemplate.getJdbcOperations().execute(
				"CREATE ALIAS IF NOT EXISTS SIMILARITY FOR 'tum.devops.http418.TestConfig.h2Similarity'");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS semesters (
				    id INT PRIMARY KEY, semester_key TEXT NOT NULL, academic_year_id INT,
				    semester_type TEXT, designation_default TEXT, start_date DATE, end_date DATE)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS course_types (
				    id BIGINT PRIMARY KEY, "key" TEXT NOT NULL UNIQUE, "name" TEXT)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS persons (
				    id BIGINT PRIMARY KEY, person_id BIGINT, first_name TEXT, last_name TEXT, business_card_url TEXT)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS organizations (
				    id BIGINT PRIMARY KEY, identification_name TEXT UNIQUE, name_ger TEXT, name_en TEXT,
				    parent_id BIGINT, org_page_url TEXT)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS courses (
				    id BIGINT PRIMARY KEY, semester_id BIGINT, course_type_id BIGINT, organization_id BIGINT,
				    title_ger TEXT, title_en TEXT, identity_code_id BIGINT, sws INT,
				    description_ger TEXT, description_en TEXT, previous_knowledge_ger TEXT, previous_knowledge_en TEXT,
				    course_objective_ger TEXT, course_objective_en TEXT, recommended_literature_ger TEXT,
				    recommended_literature_en TEXT, teaching_method_ger TEXT, teaching_method_en TEXT,
				    registration_info TEXT, raw_source_simple TEXT, raw_source_detailed TEXT,
				    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS lectureship (
				    id BIGINT PRIMARY KEY, course_id BIGINT NOT NULL, person_id BIGINT NOT NULL, teaching_function TEXT)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS course_appointments (
				    id BIGINT PRIMARY KEY, course_id BIGINT NOT NULL, weekday_key TEXT,
				    time_from TIME, time_to TIME, place TEXT, is_series BOOLEAN DEFAULT false,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS curriculum_connections (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, course_id BIGINT NOT NULL,
				    curriculum_version_id INT, study_name_ger TEXT, study_name_en TEXT,
				    study_id TEXT NOT NULL, designation BIGINT, subject_type TEXT, path TEXT,
				    source_xml TEXT, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    UNIQUE (course_id, study_id))
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS study_programs (
				    stp_id INT PRIMARY KEY,
				    name TEXT NOT NULL,
				    degree TEXT NOT NULL,
				    version TEXT,
				    status TEXT,
				    total_ects INT,
				    title TEXT,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS program_requirement_areas (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    stp_id INT NOT NULL REFERENCES study_programs (stp_id) ON DELETE CASCADE,
				    area_name TEXT NOT NULL,
				    ects INT,
				    sort_order INT NOT NULL DEFAULT 0,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    UNIQUE (stp_id, area_name)
				)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				CREATE TABLE IF NOT EXISTS program_area_courses (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    stp_id INT NOT NULL REFERENCES study_programs (stp_id) ON DELETE CASCADE,
				    area_name TEXT NOT NULL,
				    course_id BIGINT NOT NULL,
				    ects INT,
				    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    UNIQUE (stp_id, area_name, course_id)
				)
				""");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO study_programs (stp_id, name, degree, version, status, total_ects) KEY(stp_id) VALUES (5371, 'Informatik', 'Bachelor', '20241', 'active', 180)");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO study_programs (stp_id, name, degree, version, status, total_ects) KEY(stp_id) VALUES (5217, 'Informatik', 'Master', '20231', 'active', 120)");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO program_area_courses (stp_id, area_name, course_id) KEY(stp_id, area_name, course_id) VALUES (5371, 'Required Modules', 100)");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO program_area_courses (stp_id, area_name, course_id) KEY(stp_id, area_name, course_id) VALUES (5371, 'Elective Modules', 101)");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO semesters (id, semester_key, semester_type) KEY(id) VALUES (1, '25S', 'S')");
		jdbcTemplate.getJdbcOperations()
				.execute("MERGE INTO course_types (id, \"key\", \"name\") KEY(id) VALUES (1, 'VO', 'Vorlesung')");
		jdbcTemplate.getJdbcOperations()
				.execute("MERGE INTO course_types (id, \"key\", \"name\") KEY(id) VALUES (2, 'SE', 'Seminar')");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO organizations (id, name_ger, name_en) KEY(id) VALUES (1, 'Informatik', 'Computer Science')");
		jdbcTemplate.getJdbcOperations()
				.execute(
						"MERGE INTO organizations (id, name_ger, name_en) KEY(id) VALUES (2, 'Mathematik', 'Mathematics')");
		jdbcTemplate.getJdbcOperations().execute("""
				MERGE INTO courses (id, semester_id, course_type_id, organization_id, title_ger, title_en, sws) KEY(id)
				VALUES (100, 1, 1, 1, 'Einfuehrung in die Informatik', 'Introduction to Computer Science', 4)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				MERGE INTO courses (id, semester_id, course_type_id, organization_id, title_ger, title_en, sws) KEY(id)
				VALUES (101, 1, 2, 1, 'Software Engineering', 'Software Engineering', 3)
				""");
		jdbcTemplate.getJdbcOperations().execute("""
				MERGE INTO courses (id, semester_id, course_type_id, organization_id, title_ger, title_en, sws) KEY(id)
				VALUES (102, 1, 1, 2, 'Lineare Algebra', 'Linear Algebra', 4)
				""");
		jdbcTemplate.getJdbcOperations().execute(
				"""
						MERGE INTO curriculum_connections (course_id, study_name_ger, study_name_en, study_id, subject_type) KEY(course_id, study_id)
						VALUES (100, 'Informatik Bachelor', 'Computer Science BSc', '522', 'Pflichtfach')
						""");
		jdbcTemplate.getJdbcOperations().execute(
				"""
						MERGE INTO curriculum_connections (course_id, study_name_ger, study_name_en, study_id, subject_type) KEY(course_id, study_id)
						VALUES (101, 'Informatik Bachelor', 'Computer Science BSc', '522', 'Wahlfach')
						""");
		jdbcTemplate.getJdbcOperations().execute(
				"""
						MERGE INTO curriculum_connections (course_id, study_name_ger, study_name_en, study_id, subject_type) KEY(course_id, study_id)
						VALUES (102, 'Mathematik Bachelor', 'Mathematics BSc', '523', 'Pflichtfach')
						""");
		jdbcTemplate.getJdbcOperations()
				.execute("MERGE INTO persons (id, first_name, last_name) KEY(id) VALUES (1, 'Max', 'Mustermann')");
		jdbcTemplate.getJdbcOperations().execute(
				"MERGE INTO lectureship (id, course_id, person_id, teaching_function) KEY(id) VALUES (1, 100, 1, 'Dozent')");
		jdbcTemplate.getJdbcOperations().execute(
				"""
						MERGE INTO course_appointments (id, course_id, weekday_key, time_from, time_to, place, is_series) KEY(id)
						VALUES (1, 100, 'MON', '10:00', '12:00', 'Room 101', true)
						""");
		return jdbcTemplate;
	}
}
