export {
	AuthError,
	clearAccessToken,
	clearTokens,
	getAccessToken,
	hydrateAuth,
	isAuthenticated,
	login,
	logout,
	refreshAccessToken,
	setAccessToken,
	setTokens,
} from "#/api/auth";
export { getDepartments, getStudyPrograms } from "#/api/catalog";
export type { ApiFetchOptions } from "#/api/client";
export { ApiError, apiFetch } from "#/api/client";
export {
	checkPrerequisites,
	getCourse,
	getCoursePrerequisites,
	getCourses,
} from "#/api/courses";
export { getDashboard } from "#/api/dashboard";
export { getProfile, patchProfile, updateProfile } from "#/api/profile";
export {
	addCompletedCourse,
	dropCourse,
	enrollCourse,
	getCompletedCourses,
	getEnrolledCourses,
	getProgress,
	getRequirements,
	removeCompletedCourse,
	uploadTranscript,
} from "#/api/progress";
export { queryClient } from "#/api/query-client";
export {
	generateRecommendations,
	getRecommendations,
} from "#/api/recommendations";
export {
	addCourseToSemester,
	generateRoadmap,
	getRoadmap,
	getSemester,
	getSemesters,
	removeCourseFromSemester,
	updateRoadmap,
	updateSemester,
} from "#/api/roadmap";
export type {
	AcademicProgress,
	AddCompletedCourseRequest,
	AddCourseRequest,
	AlertSeverity,
	AlertType,
	AuthResponse,
	CompletedCourse,
	CourseDetail,
	CourseLevel,
	CoursePrerequisiteRef,
	CourseScheduleEntry,
	CourseSearchParams,
	CourseSession,
	CourseStatus,
	CourseStudyProgramRef,
	CourseSummary,
	Dashboard,
	DashboardAlert,
	DashboardProgress,
	DashboardRecommendation,
	DashboardRequirement,
	DegreeRequirements,
	Department,
	EnrollCourseRequest,
	EnrolledCourse,
	GenerateRoadmapRequest,
	GenerateRecommendationsBody,
	ImportError,
	ImportedCourse,
	Instructor,
	IsoDateString,
	Language,
	LoginRequest,
	Page,
	PlannedCourse,
	PreferredSemester,
	PrerequisiteCheck,
	PrerequisiteCheckRef,
	PrerequisiteNode,
	PrerequisiteTree,
	PrerequisiteType,
	ProblemDetail,
	Recommendation,
	RecommendationList,
	RecommendationParams,
	RequirementAlert,
	RequirementCategory,
	RequirementCourse,
	Roadmap,
	RoadmapStatus,
	ScheduleSlot,
	ScheduleType,
	SemesterKey,
	SemesterPlanDetail,
	StudentProfile,
	StudentProfileUpdate,
	StudyProgram,
	StudyProgramRef,
	TranscriptImportResult,
	UpcomingCourse,
} from "#/api/types";
