export {
	AuthError,
	clearAccessToken,
	clearTokens,
	getAccessToken,
	hydrateAuth,
	isAuthenticated,
	login,
	logout,
	refreshAccessToken,
	setAccessToken,
	setTokens,
} from "#/api/auth";
export { getDepartments, getStudyPrograms } from "#/api/catalog";
export type { ApiFetchOptions } from "#/api/client";
export { ApiError, apiFetch } from "#/api/client";
export {
	checkPrerequisites,
	getCourse,
	getCoursePrerequisites,
	getCourses,
} from "#/api/courses";
export { getDashboard } from "#/api/dashboard";
export {
	addCompletedCourse,
	dropCourse,
	enrollCourse,
	getCompletedCourses,
	getEnrolledCourses,
	getProgress,
	getRequirements,
	removeCompletedCourse,
	uploadTranscript,
} from "#/api/progress";
export { queryClient } from "#/api/query-client";
export { getSchedule } from "#/api/schedule";
export type {
	AcademicProgress,
	AddCompletedCourseRequest,
	AlertSeverity,
	AlertType,
	AuthResponse,
	CompletedCourse,
	CourseDetail,
	CourseLevel,
	CoursePrerequisiteRef,
	CourseScheduleEntry,
	CourseSearchParams,
	CourseSession,
	CourseStatus,
	CourseStudyProgramRef,
	CourseSummary,
	Dashboard,
	DashboardAlert,
	DashboardProgress,
	DashboardRecommendation,
	DashboardRequirement,
	DegreeRequirements,
	Department,
	EnrollCourseRequest,
	EnrolledCourse,
	ImportError,
	ImportedCourse,
	Instructor,
	IsoDateString,
	Language,
	LoginRequest,
	Page,
	PreferredSemester,
	PrerequisiteCheck,
	PrerequisiteCheckRef,
	PrerequisiteNode,
	PrerequisiteTree,
	PrerequisiteType,
	ProblemDetail,
	RequirementAlert,
	RequirementCategory,
	RequirementCourse,
	ScheduleConflict,
	ScheduleEvent,
	ScheduleEventType,
	ScheduleSlot,
	ScheduleType,
	SemesterKey,
	StudyProgram,
	TranscriptImportResult,
	UpcomingCourse,
	WeeklySchedule,
} from "#/api/types";
