apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace }}
  labels:
    app: client
    {{- include "aidan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.client }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: client
          image: {{ printf "%s/%s/%s/client:%s" .Values.image.registry .Values.image.org .Values.image.repo .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
