apiVersion: v1
kind: Secret
metadata:
  name: aidan-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.SPRING_DATASOURCE_PASSWORD }}
  APP_JWT_SECRET: {{ .Values.secrets.APP_JWT_SECRET }}
  DB_PASS: {{ .Values.secrets.DB_PASS}}
  LOGOS_API_KEY: {{ .Values.secrets.LOGOS_API_KEY }}