apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.namespace }}
  labels:
    app: server
    {{- include "aidan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.server }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          command: ["sh", "-c", "until pg_isready -h postgres-service -p {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: server
          image: {{ printf "%s/%s/%s/server:%s" .Values.image.registry .Values.image.org .Values.image.repo .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: aidan-config
            - secretRef:
                name: aidan-secret
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.server.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
