apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    {{- include "aidan-monitoring.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        {{- toYaml .Values.loki.securityContext | nindent 8 }}
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          ports:
            - containerPort: {{ .Values.loki.port }}
          args:
            - -config.file=/etc/loki/loki-config.yaml
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.loki.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.loki.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml
            - name: loki-storage
              mountPath: /loki
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: loki
  ports:
    - port: {{ .Values.loki.port }}
      targetPort: {{ .Values.loki.port }}
