apiVersion: v1
kind: Secret
metadata:
  name: aidan-monitoring-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminUser | default "admin" | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ required "grafana.adminPassword is required" .Values.grafana.adminPassword | quote }}
  DATA_SOURCE_NAME: {{ printf "postgresql://%s:%s@%s.%s.svc.cluster.local:5432/%s?sslmode=disable" .Values.postgresExporter.username .Values.postgresExporter.password .Values.postgresExporter.host .Values.appNamespace .Values.postgresExporter.database | quote }}
