apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: aidan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        monitoring: "true"
    spec:
      containers:
        - name: server
          image: ghcr.io/aet-devops26/team-http-418/server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: aidan-config
            - secretRef:
                name: aidan-secret
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: aidan
  labels:
    app: server
    monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
