server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-pods

    static_configs:
      - targets:
          - localhost
        labels:
          job: kubernetes-pods
          __path__: /var/log/pods/*/*/*.log

    relabel_configs:
      - source_labels: ['__path__']
        regex: '/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^/]+)/.*'
        target_label: namespace
        replacement: '$1'

      - source_labels: ['__path__']
        regex: '/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^/]+)/.*'
        target_label: pod
        replacement: '$2'

      - source_labels: ['__path__']
        regex: '/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^/]+)/.*'
        target_label: container
        replacement: '$4'

    pipeline_stages:
      - cri: {}