namespace: aidan-monitoring
appNamespace: aidan

ingress:
  enabled: true
  className: nginx
  host: "aidan-monitoring.stud.k8s.aet.cit.tum.de"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  tls:
    enabled: true
    secretName: aidan-tls
    clusterIssuer: letsencrypt-prod