export {
	createConversation,
	getConversation,
	getConversations,
	getSuggestions,
	sendMessage,
} from "#/api/advisor";
export {
	AuthError,
	clearAccessToken,
	clearTokens,
	getAccessToken,
	hydrateAuth,
	isAuthenticated,
	login,
	logout,
	refreshAccessToken,
	register,
	setAccessToken,
	setTokens,
} from "#/api/auth";
export { getDepartments, getStudyPrograms } from "#/api/catalog";
export type { ApiFetchOptions } from "#/api/client";
export { ApiError, apiFetch } from "#/api/client";
export {
	checkPrerequisites,
	getCourse,
	getCoursePrerequisites,
	getCoursePrerequisitesBatch,
	getCourses,
} from "#/api/courses";
export { getProfile, updateProfile } from "#/api/profile";
export {
	addCompletedCourse,
	aiMatchTranscript,
	dropCourse,
	enrollCourse,
	getCompletedCourses,
	getEnrolledCourses,
	getProgress,
	getRequirements,
	removeCompletedCourse,
	uploadTranscript,
} from "#/api/progress";
export { queryClient } from "#/api/query-client";
export {
	generateRecommendations,
	getRecommendations,
} from "#/api/recommendations";
export { generateRoadmap, getRoadmap } from "#/api/roadmap";
export { getSchedule } from "#/api/schedule";
export type {
	AcademicProgress,
	AddCompletedCourseRequest,
	AdvisorSSEEvent,
	AiMatchModule,
	AiMatchResponse,
	AiMatchResult,
	AlertSeverity,
	AlertType,
	AuthResponse,
	CompletedCourse,
	Conversation,
	ConversationMessage,
	ConversationSummary,
	CourseDetail,
	CourseLevel,
	CoursePrerequisiteRef,
	CourseScheduleEntry,
	CourseSearchParams,
	CourseSession,
	CourseStatus,
	CourseStudyProgramRef,
	CourseSummary,
	DashboardAlert,
	DegreeRequirements,
	Department,
	EnrollCourseRequest,
	EnrolledCourse,
	GenerateRecommendationsBody,
	ImportError,
	ImportedCourse,
	Instructor,
	IsoDateString,
	Language,
	LoginRequest,
	MessageRole,
	Page,
	PlannedCourse,
	PreferredSemester,
	PrerequisiteBatchResponse,
	PrerequisiteCheck,
	PrerequisiteCheckRef,
	PrerequisiteNode,
	PrerequisiteTree,
	PrerequisiteType,
	ProblemDetail,
	Recommendation,
	RecommendationList,
	RecommendationParams,
	ReferencedCourse,
	RequirementAlert,
	RequirementCategory,
	RequirementCourse,
	Roadmap,
	RoadmapStatus,
	ScheduleConflict,
	ScheduleEvent,
	ScheduleEventType,
	ScheduleSlot,
	ScheduleType,
	SemesterKey,
	SemesterPlanDetail,
	StudentProfile,
	StudyProgram,
	StudyProgramRef,
	SuggestedPrompt,
	TranscriptImportResult,
	UpcomingCourse,
	WeeklySchedule,
} from "#/api/types";
